create new branch (works-aboutme) and add projects and aboutme content
yusufnviiri/mobile-view pull request #3
Opened 2022-02-18 03:34 UTC by yusufnviiri

-create new branch works-aboutme
-add personal projects into index.html
-add about-me details
-modified style.css file

2022-02-18 05:42 UTC, Kingstalux requested changes
Hi @yusufnviiri , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-18 05:42 UTC, Kingstalux commented on index.html
> +        <section class="works">
- [ ] Good job so far with the design 👍 but you'll notice that the bottom-left of the first page is curved and the background color also changes from white to grey as indicated in the template. It would be nice if you could address this issue so as to follow the template design.
- Your design:
![Capture3](https://user-images.githubusercontent.com/85113567/154621601-fa9c8993-ef0b-49f4-89c5-54ea9d6bf976.PNG)
- Figma design:
![Capture1](https://user-images.githubusercontent.com/85113567/154621633-375dca8e-2c11-45b9-b35b-d8fb8e58a88a.PNG)

2022-02-18 05:42 UTC, Kingstalux commented on index.html
> +        <section class="works">
- [ ] The main container of the projects section should have a `display:grid`. It would be nice to implement this as it is a project requirement.

2022-02-18 05:42 UTC, Kingstalux commented on index.html
> +                    </p>
- [ ] Good job designing the project cards but you'll also notice that the card background color is different from the page background. It would be good to implement this feature.
- [ ] Also the color of your elements are not matching that of the template. It would be good to correct this too.
- Your design:
![Capture4](https://user-images.githubusercontent.com/85113567/154622532-c850ce02-6265-4997-a026-36a06d7822a8.PNG)
- Figma design:
![Capture2](https://user-images.githubusercontent.com/85113567/154622563-5fa14b79-1ec8-4521-a2a3-dd44fc467648.PNG)

2022-02-18 05:42 UTC, Kingstalux commented on index.html
> +            </article>
- [ ] Nice job designing your buttons but the background color and color of your buttons are not matching that of the template. It would be good to fix this.
- [ ] Also for a better user interface, it would be great to implement all the button interactions as shown in the Figma design.
- Button interactions:
![Capture](https://user-images.githubusercontent.com/85113567/154622942-8b2d91de-982b-4578-b570-55814b5facee.PNG)

2022-02-18 05:42 UTC, Kingstalux commented on index.html
> +                <h2>About Myself</h2>
- [ ] In the Figma design the top-right corner of the about section is curved. It would be nice to add this so as to follow the design.
- [ ] Next the container of this section should be a `section` tag and not an `article ` tag. Do well to rectify this.
- [ ] Also the heading `About myself` takes 2 lines in the design but yours is only on a single line. It would be good to correct this too.
- Your design:
![Capture6](https://user-images.githubusercontent.com/85113567/154623344-d5516f4e-0456-45a0-be6b-2bc51b4801d9.PNG)
- Figma design:
![Capture10](https://user-images.githubusercontent.com/85113567/154623375-5b656c09-02ff-4842-8dc1-e047f1b07f53.PNG)

2022-02-18 05:42 UTC, Kingstalux commented on index.html
> +                <a id="connect" href="index.html">LET'S CONNECT</a>
- [ ] Good job in this section but your paragraph has the wrong color. It would be good to verify the right color in the Figma template.
- [ ] Also the text `LET'S CONNECT` is a heading and as a result, it should use an `hx` tag like a `h2` tag for best semantic practices. Also make sure to apply its right color from the template 👍 
- [ ] Your icons are not aligned like on the template. It would be great if you could address that.
- [ ] The `Get my resume` button also needs some extra styling so that it can follow the template design. Do well to rectify that 💯 
- Your design:
![Capture7](https://user-images.githubusercontent.com/85113567/154623837-20ea03c6-75dc-45ce-9ee5-e33c01178874.PNG)
- Figma design:
![Capture9](https://user-images.githubusercontent.com/85113567/154623863-99f111f2-a35f-49b8-aef8-3a5fb05c14f9.PNG)

2022-02-18 05:42 UTC, Kingstalux commented on index.html
> +                        <img id="fram" src="images/arrow2.PNG" alt="frameworks" />
- [ ] The technology categories ("Languages", "Frameworks" and "Skills") should be in a `ul` tag, each of them in a `li` tag for best semantic practices.
- [ ] Kindly arrange your design to match that of Figma. Right now you skills section is not well aligned and also you have wrongly placed the forward arrow icons. Do well to rectify this issue 👍 
- Your design:
![Capture12](https://user-images.githubusercontent.com/85113567/154624618-3c4bcb29-36df-48ac-a480-ff96eb6fbdd9.PNG)
- Figma design:
![Capture11](https://user-images.githubusercontent.com/85113567/154624642-27d22769-7cd3-474b-a313-f51020096414.PNG)

2022-02-18 16:39 UTC, mahbubul14 requested changes
Hi @yusufnviiri ,

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

# Required Changes ♻️

- [ ] Check the comments under the review. :arrow_down_small: 

###  To Highlights
:heavy_check_mark: No linters error.
:heavy_check_mark: Clean code.
:heavy_check_mark: Descriptive PR title & description.

### Optional suggestions

- [ ] The commit message should be written in the imperative tense and the first letter will be capitalized. ["Fix bug" instead of "fix bug"](https://www.freecodecamp.org/news/level-you-up-to-awesome-commit-messages-a85558cb90e8)

- [ ] For readability, please add two spaces of indentation. Do not use the tab key. You did it throughout your code in the `HTML` file. Please fix it. [For the HTML & CSS best practices ](https://github.com/microverseinc/curriculum-html-css/blob/main/articles/html_css_best_practices.md)we should follow the rules.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification. You can also reach me on [slack](https://microverse-students.slack.com/team/U01J39GL614)

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2022-02-18 16:39 UTC, mahbubul14 commented on index.html
> +                    </p>
> * [ ]  Good job designing the project cards but you'll also notice that the card background color is different from the page background. It would be good to implement this feature.
> * [ ]  Also the color of your elements are not matching that of the template. It would be good to correct this too.
> * Your design:
> ![w1](https://user-images.githubusercontent.com/70483835/154718708-63fe74b7-56e5-4c40-b5ff-ee0ab0bcb223.png)

> * Figma design:
>   ![Capture2](https://user-images.githubusercontent.com/85113567/154622563-5fa14b79-1ec8-4521-a2a3-dd44fc467648.PNG)

- [ ] **As your previous reviewer requested for the changes, please work on that.** :+1:

2022-02-18 16:39 UTC, mahbubul14 commented on index.html
> +                <a id="connect1" href="index.html">LET'S CONNECT</a>
**As the previous reviewer requested, Please implement the following things:**

- [ ] In the Figma design the top-right corner of the about section is curved. It would be nice to add this so as to follow the design.

- [ ] The container of this section should be a section tag and not an article tag. Do well to rectify this.

- [ ] Also the text `LET'S CONNECT` is a heading and as a result, it should use an `hx` tag like an `h2` tag for best semantic practices. Also, make sure to apply its right color from the template :+1: 

> - **Your Implementation:**
![a1](https://user-images.githubusercontent.com/70483835/154721810-6d5cad0c-0d8c-4cf8-829d-d0ed7a1ddcf3.png)
> - **Figma Design:**
![a2](https://user-images.githubusercontent.com/70483835/154721840-20383f79-6b8a-43e0-8b51-2201a027d7d1.png)

2022-02-19 19:07 UTC, Kingstalux approved these changes
Hi @yusufnviiri , 
 
# Status: Approved :heavy_check_mark: :heavy_check_mark: :heavy_check_mark:

Good job implementing the required changes. Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-19 19:56 UTC, merged